Training run name: sandy-sweep-6 ...
Epoch [1/20] Train Loss: 2.0407, Train Acc: 23.37% | Val Loss: 1.9403, Val Acc: 30.66%
Epoch [2/20] Train Loss: 1.7330, Train Acc: 36.39% | Val Loss: 1.7823, Val Acc: 42.30%
Epoch [3/20] Train Loss: 1.5442, Train Acc: 44.57% | Val Loss: 1.2326, Val Acc: 57.49%
Epoch [4/20] Train Loss: 1.4326, Train Acc: 48.65% | Val Loss: 1.3257, Val Acc: 55.32%
Epoch [5/20] Train Loss: 1.3531, Train Acc: 51.56% | Val Loss: 1.1308, Val Acc: 61.32%
Epoch [6/20] Train Loss: 1.3031, Train Acc: 53.60% | Val Loss: 1.1528, Val Acc: 62.09%
Epoch [7/20] Train Loss: 1.2596, Train Acc: 55.49% | Val Loss: 1.1612, Val Acc: 62.23%
Epoch [8/20] Train Loss: 1.2166, Train Acc: 57.17% | Val Loss: 1.0233, Val Acc: 65.15%
Epoch [9/20] Train Loss: 1.1913, Train Acc: 58.04% | Val Loss: 0.9101, Val Acc: 69.23%
Epoch [10/20] Train Loss: 1.1523, Train Acc: 59.68% | Val Loss: 0.9451, Val Acc: 68.80%
Epoch [11/20] Train Loss: 1.1219, Train Acc: 60.42% | Val Loss: 0.9163, Val Acc: 69.53%
Epoch [12/20] Train Loss: 1.1009, Train Acc: 61.42% | Val Loss: 0.9140, Val Acc: 69.52%
Epoch [13/20] Train Loss: 1.0800, Train Acc: 62.30% | Val Loss: 0.8706, Val Acc: 71.53%
Epoch [14/20] Train Loss: 1.0645, Train Acc: 62.54% | Val Loss: 0.8323, Val Acc: 72.65%
Epoch [15/20] Train Loss: 1.0406, Train Acc: 63.79% | Val Loss: 0.8604, Val Acc: 71.21%
Epoch [16/20] Train Loss: 1.0320, Train Acc: 64.04% | Val Loss: 0.8366, Val Acc: 73.08%
Epoch [17/20] Train Loss: 1.0079, Train Acc: 64.78% | Val Loss: 1.1018, Val Acc: 65.56%
Epoch [18/20] Train Loss: 0.9953, Train Acc: 65.05% | Val Loss: 0.7765, Val Acc: 74.25%
Epoch [19/20] Train Loss: 0.9776, Train Acc: 65.85% | Val Loss: 0.8919, Val Acc: 71.16%
Epoch [20/20] Train Loss: 0.9666, Train Acc: 66.53% | Val Loss: 0.7121, Val Acc: 76.26%
Traceback (most recent call last):
  File "C:\Users\DDA\Downloads\CS6886W-sweep\CS6886W-sweep\trainer.py", line 38, in train
    train_model(model, trainloader, testloader, config, device, wanrun)
  File "C:\Users\DDA\Downloads\CS6886W-sweep\CS6886W-sweep\utils\train.py", line 75, in train_model
    wanrun.save("model.pth", policy="now")
  File "C:\Users\DDA\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DDA\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DDA\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 444, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DDA\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 2129, in save
    return self._save(
           ^^^^^^^^^^^
  File "C:\Users\DDA\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 2188, in _save
    target_path.symlink_to(source_path)
  File "C:\Users\DDA\AppData\Local\Programs\Python\Python311\Lib\pathlib.py", line 1198, in symlink_to
    os.symlink(target, self, target_is_directory)
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\Users\\DDA\\Downloads\\CS6886W-sweep\\CS6886W-sweep\\model.pth' -> 'C:\\Users\\DDA\\Downloads\\CS6886W-sweep\\CS6886W-sweep\\wandb\\run-20251019_140347-3qnusd2f\\files\\model.pth'
